server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTime=Asia/Seoul
    username: ten
    password: 1q2w3e4r5t!
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  security:
    user:
      name: test
      password: 1234

  servlet:
    multipart:
      max-file-size: 20MB #파일 하나의 최대 용량
      max-request-size: 200MB #한 번에 동시에 보낼 수 있는 파일 용량
# 해당 경로가 없으면 오류!(아니면 자바 코드로 경로 만드는 코드 생성하기)
file:
  path: C:/springImageDir/tencoblog/upload/
      
tenco:
  key: 25c18c1ed58157a457c41fbbcfd4a2b554648395f99c3fe5dc043c03ff6fec54ebe2adfa517897ad4b1c38d9234571c335afe244d8d686f0f9b69e22bb6b6b30
    
    